# Generated by Django 5.2.7 on 2025-11-14 16:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(default='metal', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'commodities',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('is_filterable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_attributes',
            },
        ),
        migrations.CreateModel(
            name='CommodityVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(default='gram', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.commodity')),
            ],
            options={
                'db_table': 'commodity_variants',
                'unique_together': {('commodity', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeOption',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('value_slug', models.SlugField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='inventory.productattribute')),
            ],
            options={
                'db_table': 'product_attribute_options',
                'unique_together': {('attribute', 'value_slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.productcategory')),
            ],
            options={
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('warranty', models.CharField(blank=True, max_length=255)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productcategory')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku_code', models.CharField(max_length=120, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_qty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('material', models.CharField(blank=True, max_length=120)),
                ('huid', models.CharField(blank=True, max_length=120)),
                ('purity_code', models.CharField(blank=True, max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_halmark', models.BooleanField(default=False)),
                ('dimensions', models.JSONField(blank=True, null=True)),
                ('attributes_snapshot', models.JSONField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='inventory.product')),
            ],
            options={
                'db_table': 'product_skus',
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media', models.JSONField()),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='inventory.product')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='inventory.productsku')),
            ],
            options={
                'db_table': 'product_media',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SKUAttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_option', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.productattributeoption')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_attribute_options', to='inventory.productsku')),
            ],
            options={
                'db_table': 'sku_attribute_options',
            },
        ),
        migrations.CreateModel(
            name='CommodityRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('source', models.CharField(blank=True, max_length=200)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='inventory.commodityvariant')),
            ],
            options={
                'db_table': 'commodity_rates',
                'indexes': [models.Index(fields=['effective_date'], name='commodity_r_effecti_7f3461_idx'), models.Index(fields=['variant'], name='commodity_r_variant_0edae5_idx')],
                'unique_together': {('variant', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_assignments', to='inventory.product')),
            ],
            options={
                'db_table': 'product_attribute_assignments',
                'unique_together': {('product', 'attribute')},
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['slug'], name='product_cat_slug_801f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['name'], name='product_cat_name_d66187_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_4083ff_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_slug_5e91f2_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['product'], name='product_sku_product_2d3f95_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['sku_code'], name='product_sku_sku_cod_c82abe_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['stock_qty'], name='product_sku_stock_q_549d21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skuattributeoption',
            unique_together={('sku', 'attribute_option')},
        ),
    ]
