# Generated by Django 5.2.7 on 2025-11-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='sku',
        ),
        migrations.AddField(
            model_name='productmedia',
            name='media_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/media/'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
