# Generated by Django 5.2.7 on 2025-11-16 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_productmedia_sku_productmedia_media_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsku',
            name='attributes_snapshot',
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='huid',
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='images',
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='material',
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='purity_code',
        ),
        migrations.AddField(
            model_name='productsku',
            name='commodity_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skus', to='inventory.commodityvariant'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productsku',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsku',
            name='making_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productsku',
            name='sell_by_fixed_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['commodity_variant'], name='product_sku_commodi_0f00b1_idx'),
        ),
    ]
