# Generated by Django 5.2.7 on 2025-11-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_productsku_attributes_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='inventory.productsku'),
        ),
    ]
