# Generated by Django 5.2.7 on 2025-11-25 16:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityrate',
            name='cgst_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='commodityrate',
            name='delivery_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commodityrate',
            name='hallmark_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commodityrate',
            name='packaging_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commodityrate',
            name='ratti_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('5.5'), max_digits=6),
        ),
        migrations.AddField(
            model_name='commodityrate',
            name='sgst_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='commodityrate',
            name='wastage_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
