# Generated by Django 5.2.7 on 2025-11-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_commodityrate_cgst_percent_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commodityrate',
            index=models.Index(fields=['is_active'], name='commodity_r_is_acti_ff2d50_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['sell_by_fixed_price'], name='product_sku_sell_by_85737b_idx'),
        ),
    ]
