# Generated by Django 5.2.7 on 2025-12-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_commodityrate_commodity_r_is_acti_ff2d50_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commodityrate',
            name='commodity_r_is_acti_ff2d50_idx',
        ),
        migrations.RemoveField(
            model_name='commodityrate',
            name='cgst_percent',
        ),
        migrations.RemoveField(
            model_name='commodityrate',
            name='delivery_charges',
        ),
        migrations.RemoveField(
            model_name='commodityrate',
            name='hallmark_charges',
        ),
        migrations.RemoveField(
            model_name='commodityrate',
            name='packaging_charges',
        ),
        migrations.RemoveField(
            model_name='commodityrate',
            name='ratti_multiplier',
        ),
        migrations.RemoveField(
            model_name='commodityrate',
            name='sgst_percent',
        ),
        migrations.RemoveField(
            model_name='commodityrate',
            name='wastage_percent',
        ),
    ]
