# Generated by Django 5.2.7 on 2025-12-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_commodityrate_commodity_r_is_acti_ff2d50_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityrate',
            name='cgst_percent',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=12),
        ),
        migrations.AddField(
            model_name='commodityrate',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='commodityrate',
            name='packaging_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='commodityrate',
            name='ratti_multiplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='commodityrate',
            name='sgst_percent',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=12),
        ),
        migrations.AddField(
            model_name='commodityrate',
            name='wastage_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
