# Generated by Django 5.2.7 on 2025-12-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_commodityrate_cgst_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='hallmark_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
