# Generated by Django 5.2.7 on 2025-12-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_productsku_hallmark_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsku',
            name='hallmark_charges',
        ),
        migrations.AddField(
            model_name='commodityrate',
            name='hallmark_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
