# Generated by Django 5.2.7 on 2025-12-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_productsku_hallmark_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodityrate',
            name='delivery_charges',
        ),
        migrations.RemoveField(
            model_name='commodityrate',
            name='hallmark_charges',
        ),
        migrations.RemoveField(
            model_name='commodityrate',
            name='packaging_charges',
        ),
        migrations.AddField(
            model_name='productsku',
            name='hallmark_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productsku',
            name='packaging_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
