# Generated by Django 5.2.7 on 2026-03-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_commodityrate_delivery_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsku',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='productsku',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
