# Generated by Django 5.2.7 on 2026-03-21 19:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_productsku_discount_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_url', models.URLField(help_text='Link to YouTube, Instagram, Facebook, etc.', max_length=500)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vimeo', 'Vimeo'), ('other', 'Other')], default='youtube', max_length=50)),
                ('is_homepage_featured', models.BooleanField(default=False, help_text='Show this video on the home page.')),
                ('is_boosting_video', models.BooleanField(default=False, help_text='Show this video on products that do not have their own specific videos.')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='inventory.product')),
            ],
            options={
                'db_table': 'product_videos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product'], name='product_vid_product_b2de46_idx'), models.Index(fields=['is_homepage_featured'], name='product_vid_is_home_ca99f4_idx'), models.Index(fields=['is_boosting_video'], name='product_vid_is_boos_28f790_idx')],
            },
        ),
    ]
